# Generated by Django 3.2.16 on 2023-12-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
